### ISSUE TITLE
Suggestion for the CHANGELOG file

### ISSUE THREAD

**Issue by Sven-Seyfert** [genius257/vscode-autoit#25]
Hi @genius257 ,

I was pleased to see that you use both "SemVer" and "keepachangelog" 👍 . To increase the benefit even more, I would suggest to use the CHANGELOG.md file with the GitHub TAG comparison functionality. I mean comparison of changes between the versions/tags.

See the possible changes in my fork branch `extent-changelog-by-tag-comparison` [here](https://github.com/Sven-Seyfert/vscode-autoit/commit/49929685b6245ea6ce7170dca9f6e581cd5edfc5).

Then you can do this:
![github-comparing-changes](https://user-images.githubusercontent.com/29656921/221430587-d00bdda9-c274-4d45-b207-3e4cae6d0412.gif)

If you think this would be a easy but good improvement, please let me know. I would love to create the pull request 🤞 .

Best regards
Sven

**Comment by genius257** [comment]
Hi @Sven-Seyfert

This is a great idea, i think adding comparison links on the versions makes a lot of sense! :+1: 

Question: Why not just create the pull request with almost all you posted in this issue? You already did all the work, so worst case it is denied?

And personally i have a few changes i would request:
* I don't see the legend part being so relevant, as it is almost a copy paste from the KeepAChangelog page?
* The return to top, i can see use cases for, but it does seem to add clutter to a document, only to provide an alternative to the `Home` button on the keyboard/using the mouse to click on the scroll bar?

These changes are mostly nitpicking based on my own preferences, so other people are welcome to weigh in and change my mind, democratically.

Extra:
I did not know about the markdown link based on existing text feature, very cool

**Comment by Sven-Seyfert** [comment]
> Question: Why not just create the pull request with almost all you posted in this issue? You already did all the work, so worst case it is denied?

This is handled very differently in different projects/repositories (for different authors), that's why I first created the issue. But good to know that I also could do it directly 😅 .

> I don't see the legend part being so relevant, as it is almost a copy paste from the KeepAChangelog page?

Yes it's a copy of KeepAChangelog and not mandatory, for sure. The reason why I added this is for those who aren't familiar with KeepAChangelog and how it's intended in the changelog file.

> The return to top, i can see use cases for, but it does seem to add clutter to a document, only to provide an alternative to the `Home` button on the keyboard/using the mouse to click on the scroll bar?

I agree, the only benefit is to increases the comfort.

> These changes are mostly nitpicking based on my own preferences, so other people are welcome to weigh in and change my mind, democratically.

This is fine @genius257, I am also nitpicky sometimes with my repositories 😅 . Just tell me what should be in and what not, no pain for me.

> Extra:
I did not know about the markdown link based on existing text feature, very cool

Yes this is quite helpful (for structuring markdown links).
