### ISSUE TITLE
ServerMain string encoding

### ISSUE THREAD

**Issue by Danp2** [genius257/vscode-autoit#39]
https://github.com/genius257/vscode-autoit/blob/918b9b44d8b354b9511a69b0da8841fa8ccc0f85/client/src/main.ts#L52

This generates a string that looks like `file:///c%3A/Users/danpo/OneDrive/Documents/GitHub/vscode-autoit/server/dist/main.js` where the colon gets converted to %3A.

According to https://github.com/microsoft/vscode-extension-samples/pull/564, `toString(true)` should be used so that the string isn't encoded.

**Comment by genius257** [comment]
Hi @Danp2 😄 
This is a nice catch 😉 
I am not sure it affected my current implementation, but it can't hurt to handle this ahead of time 😄 

Just curious: why did you not make a pull request instead? 😄 

Anyway. It is now implemented, and will be released with the next relevant version iteration, as this seems to fix nothing currently 😄

**Comment by Danp2** [comment]
I didn't create a PR because I wasn't sure that this needed fixed, and it's difficult to confirm since I can't step through the code in the debugger.

**Comment by genius257** [comment]
Makes sense 😄
